import Head from 'next/head'
import Layout from '../components/layout.js'

export default function Home() {
  return (
    <Layout>
                <div className='mb-15'>
        <Head>
            <title>La coloc</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <p className="text-center text-6xl mt-5 mb-10">
            Bienvenue a la coloc De Big Draancy 
        </p>
        <div className="Container ">
            <a href="/about" >
                  <p className="text-center mt-3">A propos </p>
                  <p className="text-center mb-3">Apprends à connaitre la colocation de big Draancy</p>
            </a>
        </div>
        <div className="Container">
              <a href="/contact" >
                  <p className="text-center mt-3">Contacts </p>
                  <p className="text-center mb-3">Tu veux contacter les beaux gosses de Draancy ?</p>
              </a>
        </div>
        <div className="Container ">
          <a href="/courses" >
            <p className="text-center mt-3">Cours </p>
            <p className="text-center mb-3">Le nombre d'heures séchées par les deux bolosses</p>
          </a>    
        </div>
        <div className="Container ">
          <a href="/use-state" >
            <p className="text-center mt-3">Statistique Utilisateurs</p>
            <p className="text-center mb-3">Le nombre de cliques de l'Utilisateurs</p>
          </a>    
        </div>
        </div>
    </Layout>
  )
}
